# Generated by Django 3.2.1 on 2023-05-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
